// Mocks generated by Mockito 5.4.6 from annotations
// in smart_hydroponic_ui/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_database/firebase_database.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:smart_hydroponic_ui/core/constants/app_imports.dart' as _i7;
import 'package:smart_hydroponic_ui/core/services/firebase_service.dart' as _i5;
import 'package:smart_hydroponic_ui/core/services/sqlite_service.dart' as _i6;
import 'package:smart_hydroponic_ui/Features/ControlPanel/model/actuator_model.dart'
    as _i11;
import 'package:smart_hydroponic_ui/Features/ControlPanel/model/schedules_model.dart'
    as _i12;
import 'package:smart_hydroponic_ui/Features/login_register/model/User.dart'
    as _i9;
import 'package:smart_hydroponic_ui/Features/Sensors/model/sensor_model.dart'
    as _i10;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataSnapshot_0 extends _i1.SmartFake implements _i2.DataSnapshot {
  _FakeDataSnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAuth_2 extends _i1.SmartFake implements _i4.FirebaseAuth {
  _FakeFirebaseAuth_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseService_3 extends _i1.SmartFake
    implements _i5.FirebaseService {
  _FakeFirebaseService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSqliteService_4 extends _i1.SmartFake implements _i6.SqliteService {
  _FakeSqliteService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSensorStateMgmt_5 extends _i1.SmartFake
    implements _i7.SensorStateMgmt {
  _FakeSensorStateMgmt_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThresholdRepository_6 extends _i1.SmartFake
    implements _i7.ThresholdRepository {
  _FakeThresholdRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSensorRepository_7 extends _i1.SmartFake
    implements _i7.SensorRepository {
  _FakeSensorRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseReference_8 extends _i1.SmartFake
    implements _i2.DatabaseReference {
  _FakeDatabaseReference_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCursor_10 extends _i1.SmartFake implements _i3.QueryCursor {
  _FakeQueryCursor_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_11 extends _i1.SmartFake implements _i3.Batch {
  _FakeBatch_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i5.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> writeActuatorData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#writeActuatorData, [data]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> writeThresholdData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#writeThresholdData, [data]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.DataSnapshot> readSensorData(String? sensorKey) =>
      (super.noSuchMethod(
            Invocation.method(#readSensorData, [sensorKey]),
            returnValue: _i8.Future<_i2.DataSnapshot>.value(
              _FakeDataSnapshot_0(
                this,
                Invocation.method(#readSensorData, [sensorKey]),
              ),
            ),
          )
          as _i8.Future<_i2.DataSnapshot>);

  @override
  _i8.Stream<_i2.DatabaseEvent> listenToFirebaseNode(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#listenToFirebaseNode, [path]),
            returnValue: _i8.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i8.Stream<_i2.DatabaseEvent>);

  @override
  _i8.Future<void> setSystemMode(bool? isAutomatic) =>
      (super.noSuchMethod(
            Invocation.method(#setSystemMode, [isAutomatic]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<_i2.DatabaseEvent> listenToSystemMode() =>
      (super.noSuchMethod(
            Invocation.method(#listenToSystemMode, []),
            returnValue: _i8.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i8.Stream<_i2.DatabaseEvent>);
}

/// A class which mocks [SqliteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqliteService extends _i1.Mock implements _i6.SqliteService {
  MockSqliteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i3.Database>);

  @override
  _i8.Future<void> insertActuatorLog(Map<String, dynamic>? actuatorMap) =>
      (super.noSuchMethod(
            Invocation.method(#insertActuatorLog, [actuatorMap]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getActuatorLogs(
    String? actuatorType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActuatorLogs, [actuatorType]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> insertSensorData(Map<String, dynamic>? sensorMap) =>
      (super.noSuchMethod(
            Invocation.method(#insertSensorData, [sensorMap]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSensorData(String? sensorType) =>
      (super.noSuchMethod(
            Invocation.method(#getSensorData, [sensorType]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> insertAlert(Map<String, dynamic>? alertMap) =>
      (super.noSuchMethod(
            Invocation.method(#insertAlert, [alertMap]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAlerts(String? severity) =>
      (super.noSuchMethod(
            Invocation.method(#getAlerts, [severity]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> insertScheduledTask(Map<String, dynamic>? taskMap) =>
      (super.noSuchMethod(
            Invocation.method(#insertScheduledTask, [taskMap]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getScheduledTasks(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduledTasks, [status]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> updateScheduledTaskStatus(int? id, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateScheduledTaskStatus, [id, status]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>?> getUserByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUid, [uid]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> setSystemSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSystemSetting, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getSystemSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemSetting, [key]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);
}

/// A class which mocks [SchedulerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchedulerService extends _i1.Mock implements _i7.SchedulerService {
  MockSchedulerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseAuth),
            returnValue: _FakeFirebaseAuth_2(
              this,
              Invocation.getter(#firebaseAuth),
            ),
          )
          as _i4.FirebaseAuth);

  @override
  _i8.Future<_i4.User?> registerFirebase({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerFirebase, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i4.User?>.value(),
          )
          as _i8.Future<_i4.User?>);

  @override
  _i8.Future<_i4.User?> loginFirebase({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginFirebase, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i4.User?>.value(),
          )
          as _i8.Future<_i4.User?>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logoutFirebase() =>
      (super.noSuchMethod(
            Invocation.method(#logoutFirebase, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveUserSQLite(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserSQLite, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.User?> getUserSQLite(String? uid, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSQLite, [uid, email]),
            returnValue: _i8.Future<_i9.User?>.value(),
          )
          as _i8.Future<_i9.User?>);

  @override
  _i8.Future<void> updateUserSQLite(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserSQLite, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveNotifications(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotifications, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadNotifications(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#loadNotifications, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveToSharedPreferences(String? email, String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#saveToSharedPreferences, [email, uid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getSavedEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedEmail, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getSavedUid() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedUid, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> clearSharedPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#clearSharedPreferences, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [SensorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorRepository extends _i1.Mock implements _i7.SensorRepository {
  MockSensorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseService get firebaseService =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseService),
            returnValue: _FakeFirebaseService_3(
              this,
              Invocation.getter(#firebaseService),
            ),
          )
          as _i5.FirebaseService);

  @override
  _i6.SqliteService get sqliteService =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteService),
            returnValue: _FakeSqliteService_4(
              this,
              Invocation.getter(#sqliteService),
            ),
          )
          as _i6.SqliteService);

  @override
  _i8.Future<_i10.Sensor?> fetchLastSensorReading(String? sensorType) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLastSensorReading, [sensorType]),
            returnValue: _i8.Future<_i10.Sensor?>.value(),
          )
          as _i8.Future<_i10.Sensor?>);

  @override
  _i8.Stream<List<_i10.Sensor>> listenToAllSensors() =>
      (super.noSuchMethod(
            Invocation.method(#listenToAllSensors, []),
            returnValue: _i8.Stream<List<_i10.Sensor>>.empty(),
          )
          as _i8.Stream<List<_i10.Sensor>>);

  @override
  _i8.Future<List<_i10.Sensor>> getSensorHistory(String? sensorType) =>
      (super.noSuchMethod(
            Invocation.method(#getSensorHistory, [sensorType]),
            returnValue: _i8.Future<List<_i10.Sensor>>.value(<_i10.Sensor>[]),
          )
          as _i8.Future<List<_i10.Sensor>>);
}

/// A class which mocks [ControlPanelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockControlPanelRepository extends _i1.Mock
    implements _i7.ControlPanelRepository {
  MockControlPanelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseService get firebaseService =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseService),
            returnValue: _FakeFirebaseService_3(
              this,
              Invocation.getter(#firebaseService),
            ),
          )
          as _i5.FirebaseService);

  @override
  _i6.SqliteService get sqliteService =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteService),
            returnValue: _FakeSqliteService_4(
              this,
              Invocation.getter(#sqliteService),
            ),
          )
          as _i6.SqliteService);

  @override
  _i8.Stream<_i2.DatabaseEvent> listenToActuator(String? actuatorType) =>
      (super.noSuchMethod(
            Invocation.method(#listenToActuator, [actuatorType]),
            returnValue: _i8.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i8.Stream<_i2.DatabaseEvent>);

  @override
  _i8.Future<void> sendActuatorCommand(_i11.Actuator? actuator) =>
      (super.noSuchMethod(
            Invocation.method(#sendActuatorCommand, [actuator]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i11.Actuator>> getActuatorHistory(String? actuatorType) =>
      (super.noSuchMethod(
            Invocation.method(#getActuatorHistory, [actuatorType]),
            returnValue: _i8.Future<List<_i11.Actuator>>.value(
              <_i11.Actuator>[],
            ),
          )
          as _i8.Future<List<_i11.Actuator>>);

  @override
  _i8.Future<void> emergencyStop(List<_i11.Actuator>? actuators) =>
      (super.noSuchMethod(
            Invocation.method(#emergencyStop, [actuators]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addScheduledTask(_i12.ScheduledTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#addScheduledTask, [task]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ThresholdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThresholdRepository extends _i1.Mock
    implements _i7.ThresholdRepository {
  MockThresholdRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseService get firebaseService =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseService),
            returnValue: _FakeFirebaseService_3(
              this,
              Invocation.getter(#firebaseService),
            ),
          )
          as _i5.FirebaseService);

  @override
  _i8.Future<void> saveThreshold(_i7.SensorThreshold? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#saveThreshold, [threshold]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i7.SensorThreshold>> listenToThresholds() =>
      (super.noSuchMethod(
            Invocation.method(#listenToThresholds, []),
            returnValue: _i8.Stream<List<_i7.SensorThreshold>>.empty(),
          )
          as _i8.Stream<List<_i7.SensorThreshold>>);
}

/// A class which mocks [AlertsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertsRepository extends _i1.Mock implements _i7.AlertsRepository {
  MockAlertsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SqliteService get sqliteService =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteService),
            returnValue: _FakeSqliteService_4(
              this,
              Invocation.getter(#sqliteService),
            ),
          )
          as _i6.SqliteService);

  @override
  _i7.SensorStateMgmt get sensorStateMgmt =>
      (super.noSuchMethod(
            Invocation.getter(#sensorStateMgmt),
            returnValue: _FakeSensorStateMgmt_5(
              this,
              Invocation.getter(#sensorStateMgmt),
            ),
          )
          as _i7.SensorStateMgmt);

  @override
  void monitorSensorStatusChanges() => super.noSuchMethod(
    Invocation.method(#monitorSensorStatusChanges, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<List<_i7.Alert>> getAllAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlerts, []),
            returnValue: _i8.Future<List<_i7.Alert>>.value(<_i7.Alert>[]),
          )
          as _i8.Future<List<_i7.Alert>>);

  @override
  _i8.Future<List<_i7.Alert>> getAlertsBySeverity(String? severity) =>
      (super.noSuchMethod(
            Invocation.method(#getAlertsBySeverity, [severity]),
            returnValue: _i8.Future<List<_i7.Alert>>.value(<_i7.Alert>[]),
          )
          as _i8.Future<List<_i7.Alert>>);

  @override
  _i8.Future<void> markAsRead(int? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [alertId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);
}

/// A class which mocks [SettingsStateMgmt].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsStateMgmt extends _i1.Mock implements _i7.SettingsStateMgmt {
  MockSettingsStateMgmt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ThresholdRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeThresholdRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.ThresholdRepository);

  @override
  List<_i7.SensorThreshold> get thresholds =>
      (super.noSuchMethod(
            Invocation.getter(#thresholds),
            returnValue: <_i7.SensorThreshold>[],
          )
          as List<_i7.SensorThreshold>);

  @override
  set thresholds(List<_i7.SensorThreshold>? value) => super.noSuchMethod(
    Invocation.setter(#thresholds, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> updateThreshold(_i7.SensorThreshold? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#updateThreshold, [threshold]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SensorStateMgmt].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorStateMgmt extends _i1.Mock implements _i7.SensorStateMgmt {
  MockSensorStateMgmt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.SensorRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSensorRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.SensorRepository);

  @override
  List<_i10.Sensor> get sensors =>
      (super.noSuchMethod(
            Invocation.getter(#sensors),
            returnValue: <_i10.Sensor>[],
          )
          as List<_i10.Sensor>);

  @override
  Map<String, List<_i10.Sensor>> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <String, List<_i10.Sensor>>{},
          )
          as Map<String, List<_i10.Sensor>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set sensors(List<_i10.Sensor>? value) => super.noSuchMethod(
    Invocation.setter(#sensors, value),
    returnValueForMissingStub: null,
  );

  @override
  set history(Map<String, List<_i10.Sensor>>? value) => super.noSuchMethod(
    Invocation.setter(#history, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setCalibration(_i7.SensorCalibration? calibration) =>
      (super.noSuchMethod(
            Invocation.method(#setCalibration, [calibration]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  double getCalibration(String? sensorType) =>
      (super.noSuchMethod(
            Invocation.method(#getCalibration, [sensorType]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getCalibratedValue(String? sensorType, double? rawValue) =>
      (super.noSuchMethod(
            Invocation.method(#getCalibratedValue, [sensorType, rawValue]),
            returnValue: 0.0,
          )
          as double);

  @override
  void updateSensorReading(String? sensorType, double? rawValue) =>
      super.noSuchMethod(
        Invocation.method(#updateSensorReading, [sensorType, rawValue]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseEvent extends _i1.Mock implements _i2.DatabaseEvent {
  MockDatabaseEvent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseEventType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i2.DatabaseEventType.childAdded,
          )
          as _i2.DatabaseEventType);

  @override
  _i2.DataSnapshot get snapshot =>
      (super.noSuchMethod(
            Invocation.getter(#snapshot),
            returnValue: _FakeDataSnapshot_0(
              this,
              Invocation.getter(#snapshot),
            ),
          )
          as _i2.DataSnapshot);
}

/// A class which mocks [DataSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSnapshot extends _i1.Mock implements _i2.DataSnapshot {
  MockDataSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseReference get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeDatabaseReference_8(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.DatabaseReference);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  Iterable<_i2.DataSnapshot> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: <_i2.DataSnapshot>[],
          )
          as Iterable<_i2.DataSnapshot>);

  @override
  bool hasChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#hasChild, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.DataSnapshot child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeDataSnapshot_0(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i2.DataSnapshot);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i3.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  _i3.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_1(this, Invocation.getter(#database)),
          )
          as _i3.Database);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> transaction<T>(
    _i8.Future<T> Function(_i3.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action], {#exclusive: exclusive}),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> readTransaction<T>(
    _i8.Future<T> Function(_i3.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readTransaction, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> devInvokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeMethod, [method, arguments]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawInsert, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i3.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [table, values],
              {
                #nullColumnHack: nullColumnHack,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i8.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i8.Future<List<Map<String, Object?>>>);

  @override
  _i8.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i8.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i8.Future<List<Map<String, Object?>>>);

  @override
  _i8.Future<_i3.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
            returnValue: _i8.Future<_i3.QueryCursor>.value(
              _FakeQueryCursor_10(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.QueryCursor>);

  @override
  _i8.Future<_i3.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
            returnValue: _i8.Future<_i3.QueryCursor>.value(
              _FakeQueryCursor_10(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i3.QueryCursor>);

  @override
  _i8.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i3.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, values],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i3.Batch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeBatch_11(this, Invocation.method(#batch, [])),
          )
          as _i3.Batch);
}
