// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIVrHGIIgPuRtSsPc3XVfnWkewxruHXs',
    appId: '1:1054318018958:web:78b8a3f5bce958df35e4df',
    messagingSenderId: '1054318018958',
    projectId: 'smart-hydroponic-72272',
    authDomain: 'smart-hydroponic-72272.firebaseapp.com',
    storageBucket: 'smart-hydroponic-72272.firebasestorage.app',
    measurementId: 'G-3Y2ZZVB9BZ',
    databaseURL: 'https://smart-hydroponic-72272-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41_sX-k7gbOHYytVa-pQvQs7kElwSfFw',
    appId: '1:1054318018958:android:87f11461f8b94bb935e4df',
    messagingSenderId: '1054318018958',
    projectId: 'smart-hydroponic-72272',
    storageBucket: 'smart-hydroponic-72272.firebasestorage.app',
    databaseURL: 'https://smart-hydroponic-72272-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBow78zx0EVtBX6VULEaMJXMcKCu7rF90I',
    appId: '1:1054318018958:ios:3c9541c78ef0a07735e4df',
    messagingSenderId: '1054318018958',
    projectId: 'smart-hydroponic-72272',
    storageBucket: 'smart-hydroponic-72272.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponicUi',
    databaseURL: 'https://smart-hydroponic-72272-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBow78zx0EVtBX6VULEaMJXMcKCu7rF90I',
    appId: '1:1054318018958:ios:3c9541c78ef0a07735e4df',
    messagingSenderId: '1054318018958',
    projectId: 'smart-hydroponic-72272',
    storageBucket: 'smart-hydroponic-72272.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponicUi',
    databaseURL: 'https://smart-hydroponic-72272-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlIVrHGIIgPuRtSsPc3XVfnWkewxruHXs',
    appId: '1:1054318018958:web:a50236a3bdc0ca2d35e4df',
    messagingSenderId: '1054318018958',
    projectId: 'smart-hydroponic-72272',
    authDomain: 'smart-hydroponic-72272.firebaseapp.com',
    storageBucket: 'smart-hydroponic-72272.firebasestorage.app',
    measurementId: 'G-3P4Q08KLMK',
    databaseURL: 'https://smart-hydroponic-72272-default-rtdb.firebaseio.com',
  );
}
